name: Build WebBoot Companion

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    strategy:
      fail-fast: false 
      matrix:
        platform: [windows-latest, macos-latest]

    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install dependencies (macOS)
        if: matrix.platform == 'macos-latest'
        run: |
          brew install libusb

      - name: Install dependencies (Windows)
        if: matrix.platform == 'windows-latest'
        run: |
          choco install -y libusb
          
          # Install WebView2 - required for Tauri on Windows
          choco install -y microsoft-edge-webview2
          
          # Install Visual C++ Build Tools
          choco install -y visualstudio2019buildtools visualstudio2019-workload-vctools
          
          # Show installed environment for debugging
          echo "Environment Path:"
          echo $env:PATH

      - name: Install npm dependencies
        run: |
          cd webbboot-companion
          npm install

      - name: Build Tauri app (Windows with verbose output)
        if: matrix.platform == 'windows-latest'
        run: |
          cd webbboot-companion
          npm run tauri build -- --debug
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Tauri app (macOS)
        if: matrix.platform == 'macos-latest'
        run: |
          cd webbboot-companion
          npm run tauri build --release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload artifacts (Windows)
        if: matrix.platform == 'windows-latest'
        uses: actions/upload-artifact@v4
        with:
          name: webbboot-companion-windows-latest
          path: webbboot-companion/src-tauri/target/release/bundle/nsis/*.exe

      - name: Upload artifacts (macOS)
        if: matrix.platform == 'macos-latest'
        uses: actions/upload-artifact@v4
        with:
          name: webbboot-companion-macos-latest
          path: webbboot-companion/src-tauri/target/release/bundle/dmg/*.dmg