name: Build WebBoot Companion

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    strategy:
      matrix:
        platform: [Ubuntu-20.04, Windows-Latest, macOS-Latest]

    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install dependencies (Ubuntu)
        if: matrix.platform == 'Ubuntu-20.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.0-dev \
            build-essential \
            curl \
            wget \
            libssl-dev \
            libgtk-3-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev \
            libusb-1.0-0-dev

      - name: Install dependencies (macOS)
        if: matrix.platform == 'macOS-Latest'
        run: |
          brew install libusb

      - name: Install dependencies (Windows)
        if: matrix.platform == 'Windows-Latest'
        run: |
          choco install -y libusb

      - name: Install npm dependencies
        run: |
          cd webbboot-companion
          npm install

      - name: Build Tauri app
        run: |
          cd webbboot-companion
          npm run tauri build --release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload artifacts (Ubuntu)
        if: matrix.platform == 'Ubuntu-20.04'
        uses: actions/upload-artifact@v4
        with:
          name: webbboot-companion-ubuntu-latest
          path: |
            webbboot-companion/src-tauri/target/release/bundle/deb/*.deb
            webbboot-companion/src-tauri/target/release/bundle/rpm/*.rpm

      - name: Upload artifacts (Windows)
        if: matrix.platform == 'Windows-Latest'
        uses: actions/upload-artifact@v4
        with:
          name: webbboot-companion-windows-latest
          path: webbboot-companion/src-tauri/target/release/bundle/nsis/*.exe

      - name: Upload artifacts (macOS)
        if: matrix.platform == 'macOS-Latest'
        uses: actions/upload-artifact@v4
        with:
          name: webbboot-companion-macos-latest
          path: webbboot-companion/src-tauri/target/release/bundle/dmg/*.dmg