name: Build and Release WebBoot Companion

on:
  push:
    tags: ['v*']
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'macos-latest'
            args: '--target universal-apple-darwin'
          - platform: 'ubuntu-20.04'
            args: ''
          - platform: 'windows-latest'
            args: ''

    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-20.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf libusb-1.0-0-dev

      - name: Rust setup
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './webbboot-companion/src-tauri -> target'

      - name: Sync node version and setup cache
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'
          cache-dependency-path: './webbboot-companion/package-lock.json'

      - name: Install frontend dependencies
        working-directory: ./webbboot-companion
        run: npm ci

      - name: Build the app
        working-directory: ./webbboot-companion
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: ${{ github.ref_name }}
          releaseName: 'WebBoot Companion v__VERSION__'
          releaseBody: |
            ## WebBoot Companion v__VERSION__
            
            Cross-platform USB bootable drive creation tool.
            
            ### Download for your platform:
            - **Windows**: Download the `.exe` installer
            - **macOS**: Download the `.dmg` disk image  
            - **Linux**: Download the `.deb` (Ubuntu/Debian) or `.rpm` (Red Hat/Fedora)
            
            ### Changes in this release:
            - Enhanced USB device detection
            - Cross-platform ISO writing support
            - Improved progress tracking
            - Better error handling
          releaseDraft: false
          prerelease: false
          args: ${{ matrix.args }}
